In [15]:
import pandas as pd

# Load the dataset
file_path = '../../data/processed/merged_cycling_data.csv'
df = pd.read_csv(file_path)

#Convert ADDRESSNUMBERTEXT to string
df['ADDRESSNUMBERTEXT'] = df['ADDRESSNUMBERTEXT'].astype(str)

# Convert datetime columns to datetime type
df['datetime_bin_start'] = pd.to_datetime(df['datetime_bin_start'])
df['datetime_bin_end'] = pd.to_datetime(df['datetime_bin_end'])


# Feature selection ( dropping irrelevant columns including 'geometry')
irrelevant_features = ['_id', 'ID', 'geometry', 'index_right', 'SDE_STATE_ID','centreline_id']
df.drop(columns=irrelevant_features, inplace=True)

# Display the first few rows of the dataset
print(df.head())

C:\Users\singhg2\AppData\Local\Temp\ipykernel_47580\2996798715.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

  ADDRESSNUMBERTEXT   ADDRESSSTREET      FROMSTREET DIRECTION  WARD  BIA  \
0              46.0  Wellesley St E  Wellesley St E       NaN  13.0  NaN
1              46.0  Wellesley St E  Wellesley St E       NaN  13.0  NaN
2              46.0  Wellesley St E  Wellesley St E       NaN  13.0  NaN
3              46.0  Wellesley St E  Wellesley St E       NaN  13.0  NaN
4              46.0  Wellesley St E  Wellesley St E       NaN  13.0  NaN

  ASSETTYPE               STATUS  direction                         location  \
0      Ring  Temporarily Removed  Westbound  WELLESLEY ST E WB E OF YONGE ST
1      Ring  Temporarily Removed  Westbound  WELLESLEY ST E WB E OF YONGE ST
2      Ring  Temporarily Removed  Westbound  WELLESLEY ST E WB E OF YONGE ST
3      Ring  Temporarily Removed  Westbound  WELLESLEY ST E WB E OF YONGE ST
4      Ring  Temporarily Removed  Westbound  WELLESLEY ST E WB E OF YONGE ST

  class_type  daily_temperature  daily_precipitation  datetime_bin_start  \
0   Cyclists               11.0                  0.0 2012-04-26 21:00:00
1   Cyclists               11.0                  0.0 2012-04-26 20:00:00
2   Cyclists               18.0                  1.0 2012-05-06 02:00:00
3   Cyclists               18.0                  1.0 2012-05-06 03:00:00
4   Cyclists               18.0                  1.0 2012-05-06 04:00:00

     datetime_bin_end  volume  distance_meters
0 2012-04-26 22:00:00    11.0         175.6902
1 2012-04-26 21:00:00    31.0         175.6902
2 2012-05-06 03:00:00     4.0         175.6902
3 2012-05-06 04:00:00     1.0         175.6902
4 2012-05-06 05:00:00     5.0         175.6902

Inspect data

In [16]:




# Step 2: Inspect the dataset
print(df.describe())

               WARD  daily_temperature  daily_precipitation  \
count  1.412826e+06       1.363648e+06         1.363648e+06
mean   1.126400e+01       2.053999e+01         2.236976e+00
min    4.000000e+00       5.000000e+00         0.000000e+00
25%    1.000000e+01       1.500000e+01         0.000000e+00
50%    1.100000e+01       2.100000e+01         0.000000e+00
75%    1.300000e+01       2.600000e+01         1.000000e+00
max    1.900000e+01       3.700000e+01         5.800000e+01
std    1.951824e+00       6.494107e+00         5.898343e+00

                  datetime_bin_start               datetime_bin_end  \
count                        1413834                        1413834
mean   2015-09-01 15:12:26.165957632  2015-09-01 16:11:45.344191744
min              2010-03-17 00:00:00            2010-03-17 01:00:00
25%              2014-07-15 05:00:00            2014-07-15 06:00:00
50%              2016-06-10 10:00:00            2016-06-10 11:00:00
75%              2017-06-18 14:00:00            2017-06-18 15:00:00
max              2018-10-10 23:00:00            2018-10-11 00:00:00
std                              NaN                            NaN

             volume  distance_meters
count  1.413834e+06     1.413834e+06
mean   5.288107e+01     1.114198e+02
min    0.000000e+00     8.132257e+00
25%    8.000000e+00     6.617902e+01
50%    2.800000e+01     1.136733e+02
75%    7.200000e+01     1.575563e+02
max    7.120000e+02     1.999175e+02
std    7.276931e+01     5.223066e+01

In [17]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

#  Normalize/Scale features
scaler = StandardScaler()
numerical_features = ['daily_temperature', 'daily_precipitation', 'distance_meters']
df[numerical_features] = scaler.fit_transform(df[numerical_features])

#  Encode categorical variables
label_encoder = LabelEncoder()
categorical_features = ['ADDRESSNUMBERTEXT','ADDRESSSTREET', 'FROMSTREET', 'DIRECTION', 'WARD', 'BIA', 'ASSETTYPE', 'STATUS', 'direction', 'location', 'class_type']
for col in categorical_features:
    df[col] = label_encoder.fit_transform(df[col].astype(str))



# Now df is cleaned and ready for model training
print(df.head())

   ADDRESSNUMBERTEXT  ADDRESSSTREET  FROMSTREET  DIRECTION  WARD  BIA  \
0                507            103         259          4     3   20
1                507            103         259          4     3   20
2                507            103         259          4     3   20
3                507            103         259          4     3   20
4                507            103         259          4     3   20

   ASSETTYPE  STATUS  direction  location  class_type  daily_temperature  \
0          1       1          3        91           0          -1.469024
1          1       1          3        91           0          -1.469024
2          1       1          3        91           0          -0.391123
3          1       1          3        91           0          -0.391123
4          1       1          3        91           0          -0.391123

   daily_precipitation  datetime_bin_start    datetime_bin_end  volume  \
0            -0.379255 2012-04-26 21:00:00 2012-04-26 22:00:00    11.0
1            -0.379255 2012-04-26 20:00:00 2012-04-26 21:00:00    31.0
2            -0.209716 2012-05-06 02:00:00 2012-05-06 03:00:00     4.0
3            -0.209716 2012-05-06 03:00:00 2012-05-06 04:00:00     1.0
4            -0.209716 2012-05-06 04:00:00 2012-05-06 05:00:00     5.0

   distance_meters
0         1.230511
1         1.230511
2         1.230511
3         1.230511
4         1.230511

In [18]:
df.describe()

,ADDRESSNUMBERTEXT,ADDRESSSTREET,FROMSTREET,DIRECTION,WARD,BIA,ASSETTYPE,STATUS,direction,location,class_type,daily_temperature,daily_precipitation,datetime_bin_start,datetime_bin_end,volume,distance_meters
count,1.413834e+06,1.413834e+06,1.413834e+06,1.413834e+06,1.413834e+06,1.413834e+06,1.413834e+06,1.413834e+06,1.413834e+06,1.413834e+06,1413834.0,1.363648e+06,1.363648e+06,1413834,1413834,1.413834e+06,1.413834e+06
mean,3.704372e+02,5.604770e+01,1.345105e+02,1.580354e+00,1.453014e+00,1.627839e+01,1.020076e+00,5.621028e-02,1.127449e+00,4.269787e+01,0.0,-1.854141e-16,-1.483980e-17,2015-09-01 15:12:26.165957632,2015-09-01 16:11:45.344191744,5.288107e+01,1.138610e-16
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,-2.392939e+00,-3.792551e-01,2010-03-17 00:00:00,2010-03-17 01:00:00,0.000000e+00,-1.977528e+00
25%,2.050000e+02,2.200000e+01,5.100000e+01,0.000000e+00,0.000000e+00,1.400000e+01,1.000000e+00,0.000000e+00,0.000000e+00,1.700000e+01,0.0,-8.530803e-01,-3.792551e-01,2014-07-15 05:00:00,2014-07-15 06:00:00,8.000000e+00,-8.661737e-01
50%,3.650000e+02,5.900000e+01,1.180000e+02,2.000000e+00,1.000000e+00,1.900000e+01,1.000000e+00,0.000000e+00,1.000000e+00,3.200000e+01,0.0,7.083460e-02,-3.792551e-01,2016-06-10 10:00:00,2016-06-10 11:00:00,2.800000e+01,4.314522e-02
75%,5.470000e+02,8.600000e+01,2.200000e+02,3.000000e+00,3.000000e+00,2.000000e+01,1.000000e+00,0.000000e+00,2.000000e+00,7.300000e+01,0.0,8.407637e-01,-2.097159e-01,2017-06-18 14:00:00,2017-06-18 15:00:00,7.200000e+01,8.833225e-01
max,7.660000e+02,1.110000e+02,2.730000e+02,4.000000e+00,8.000000e+00,2.000000e+01,2.000000e+00,1.000000e+00,3.000000e+00,9.300000e+01,0.0,2.534608e+00,9.454018e+00,2018-10-10 23:00:00,2018-10-11 00:00:00,7.120000e+02,1.694364e+00
std,2.094088e+02,3.448084e+01,8.540574e+01,1.294575e+00,1.653745e+00,5.383119e+00,1.490609e-01,2.303274e-01,1.266032e+00,3.246953e+01,0.0,1.000000e+00,1.000000e+00,NaN,NaN,7.276931e+01,1.000000e+00

In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Assuming 'df' is your DataFrame
# df = pd.read_csv('your_data.csv')  # Uncomment and modify this line to load your data

# Convert datetime features to numerical features
for column in df.select_dtypes(include=['datetime64']).columns:
    df[column + '_year'] = df[column].dt.year
    df[column + '_month'] = df[column].dt.month
    df[column + '_day'] = df[column].dt.day
    df[column + '_hour'] = df[column].dt.hour
    df[column + '_minute'] = df[column].dt.minute
    df.drop(columns=[column], inplace=True)


# Fill missing values with the mean of the respective columns
df.fillna(df.mean(), inplace=True)


# Assuming 'volume' is the target variable
target = 'volume'
features = df.drop(columns=[target])
target_values = df[target]

# Convert categorical variables to dummy/indicator variables
features = pd.get_dummies(features)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target_values, test_size=0.3, random_state=42)

# Initialize the model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R^2 Score: {r2}')

Mean Squared Error: 4308.2900350036025
R^2 Score: 0.19127181593711806